import "dotenv/config";
export declare const CHROME_ENV: string;
export declare const MTKE_POD_IP: string;
export declare const MTKE_IMAGE_TAG: string;
export declare const IS_MACOS: boolean;
export declare const DEBUG: string;
export declare const baseDir: string;
export declare const LOG_PATH: string;
export declare const CACHE_DIR: string;
export declare const TASK_HISTORY_PATH: string;
export declare const ALERT_TEMP_PATH: string;
export declare const LOGIN_PATH: string;
export declare const NET_RECORD_PATH: string;
export declare const WHISTLE_PATH: string;
export declare const CHROME_PATH: string;
export declare const LOG_LEVEL: string;
export declare const MASTER_LAUNCHER_DOMAIN: string;
export declare const JINGWEI_DOMAIN: string;
export declare const JW_SERVER_API: string;
export declare const N2_IP: string;
export declare const YQQ_IP: string;
export declare const PROXY_IP: string;
export declare const PROXY_PORT: string;
export declare const USE_PROXY: string;
export declare const PROXY_STR: string;
export declare const ADMIN_NAME = "shiningding;alvabillwu;jacobren;kevinylzhao";
export declare const LOGIN_UIN: string;
export declare const LOGIN_PWD: string;
export declare const LOGIN_TIMEOUT: string | number;
export declare const maxdyncParamsLength = 5;
export declare const MD5_COMMAND: string;
export declare const SSIM_THRESHOLD_DEFAULT = 0.6;
export declare const LOGIN_REFRESH_TIM = 10800000;
export declare const CLEAR_DURATION = 8640000000;
export declare const MAX_TASK_COUNT: number;
export declare const ALERT_ID_INTERNAL: number;
export declare const ALERT_ID_LHR_UPDATE: number;
export declare const ALERT_ID_SSIM_CHANGE_NORMAL: number;
export declare const ALERT_ID_ASSESTS_ERROR: number;
export declare const CHROME_FLAGS: string[];
declare const config: {
    runners: string[];
    actions: any[];
};
export declare const initPath: (path: any) => void;
export default config;
